#downloadfile
!wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz

#extrak file
!tar xf cpuminer-opt-linux.tar.gz  

#run mining
!./cpuminer-sse2 -a YespowerSugar -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1qzn6ynjwz2rgvxaprpjy4fukknpdlpuwnzufrrq.sugaar1